sonar.projectKey=prova-app_che_protegger_e_trasforma-MVP
sonar.projectName=prova-app_che_protegger_e_trasforma-MVP
sonar.projectVersion=1.0

# Sorgenti e test
sonar.sources=src
sonar.tests=tests/unit

# Versione Python
sonar.python.version=3.12

# Report generati dal Makefile (target coverage)
sonar.python.coverage.reportPaths=coverage.xml
sonar.python.xunit.reportPath=pytest.xml

# Esclusioni
sonar.exclusions=venv/**,**/__pycache__/**
sonar.coverage.exclusions=tests/integration/**